### ISSUE TITLE
Tarea para Franco: Navegador-header 

### ISSUE THREAD

**Issue by VirginiaFalconi** [ISPCcodesquadOrganization/ISPCcodesquadOrganization.github.io#2]
- [x] Navegador
- [x] Aplicar bootstrap a navegador

@FrancoR-Orellana

**Comment by FrancoR-Orellana** [comment]
Se realiza header y se implementa bootstrap al proyecto

**Comment by FrancoR-Orellana** [comment]
Header terminado, falta definir paleta de colores
